blank_issues_enabled: false    # Ğ—Ğ°Ğ¿Ñ€ĞµÑ‚Ğ¸Ñ‚ÑŒ ÑĞ¾Ğ·Ğ´Ğ°Ğ½Ğ¸Ğµ Issues Ğ±ĞµĞ· ÑˆĞ°Ğ±Ğ»Ğ¾Ğ½Ğ°
issue_shemas:
  - name: â“ feature
    default_template : feature_request.md
    about: any features are needed
  - name: ğŸ bug_report
    default_template : bug_report.md
    about: report about a bug
  - name : refactor
    about : Suggested refactoring approach
    default_template : refactor.md
  - name : test_coverage
    about : - Unit tests, Integration tests, E2E tests
    default_template : test_coverage.md
