blank_issues_enabled: false    # Ğ—Ğ°Ğ¿Ñ€ĞµÑ‚Ğ¸Ñ‚ÑŒ ÑĞ¾Ğ·Ğ´Ğ°Ğ½Ğ¸Ğµ Issues Ğ±ĞµĞ· ÑˆĞ°Ğ±Ğ»Ğ¾Ğ½Ğ°
contact_links:
  - name: â“ question
    url: https://example.com/docs
    about: any questions about EAGLE
  - name: ğŸ bug_report
    url: https://example.com/bug-report
    about: repoert any bugs here
